namespace ElectronicsInventory;

// ============================================================
// Program.cs  –  Application Entry Point
// ============================================================
// This is the first code that runs when the application starts.
//
// STARTUP SEQUENCE:
//   1. ApplicationConfiguration.Initialize()
//        Sets up Windows Forms visual styles, DPI awareness, etc.
//        This is auto-generated by Visual Studio and should not
//        be changed.
//
//   2. DataStore.Initialize()
//        Opens a connection to the Supabase database and loads
//        all three tables (Components, Projects, Checkouts) into
//        memory. This must succeed before the app can open,
//        because every form reads data from DataStore.
//
//        If the connection fails (wrong password, no internet,
//        wrong host), a clear error dialog is shown and the app
//        exits rather than opening with empty/broken data.
//
//   3. Application.Run(new frmLogin())
//        Opens the login window and starts the Windows message
//        loop (which keeps the app running and responding to
//        button clicks, etc.).
// ============================================================

internal static class Program
{
    // [STAThread] is required by Windows Forms.
    // It sets the COM threading model to Single-Threaded Apartment,
    // which is needed for UI components like file dialogs to work correctly.
    [STAThread]
    static void Main()
    {
        // Step 1: Initialize Windows Forms settings (DPI, visual styles).
        ApplicationConfiguration.Initialize();

        // Step 2: Connect to Supabase and load all data into memory.
        // If this fails, we show an error and stop — the app cannot run
        // without a working database connection.
        try
        {
            DataStore.Initialize();
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                $"Could not open the database.\n\n{ex.Message}\n\n" +
                $"Expected location: {DatabaseConfig.DatabasePath}",
                "Database Error",
                MessageBoxButtons.OK,
                MessageBoxIcon.Error);
            return; // Exit the app — do not open the login window.
        }

        // Step 3: Open the login form. The app stays running until this
        // window (and all its child windows) are closed.
        Application.Run(new frmLogin());
    }
}
